"""Contains constants for units and standard values """
# VOLUME
LITRES = 'L'
GALLONS = 'GALLONS'  # US Gallons
CUBIC_CM = 'cc'
FLUID_OUNCE = 'fl oz'
CUBIC_FEET = 'cu ft'

# FUEL EFFICIENCY
LITRES_PER_100_KM = 'L/100km'
MILES_PER_GALLON = 'mpg'

# POWER
HORSEPOWER = 'hp'
KILLOWATT = 'kW'
NEWTON_METRE = 'Nm'
POUNDS_FEET = "lb ft"

# Mass
KILOGRAMS = 'kg'
POUNDS = 'lbs'

# LENGTH/DISTANCE
MILLIMETRES = 'mm'
CENTIMETRES = 'cm'
INCHES = 'inches'
KILOMETRES = 'km'
MILES = 'mi'

# SPEED
KILMETRES_PER_HOUR = 'kph'
MILES_PER_HOUR = 'mph'
ONE_HUNDRED_KPH = "100 kph"
SIXTY_MPH = "60 mph"

# EMISSIONS
CO2_PER_KILOMETRE = 'CO2/km'

# FUEL ECON/EMISSION TYPES
URBAN = 'URBAN'
EXTRA_URBAN = 'EXTRA_URBAN'
CITY = 'CITY'
HIGHWAY = 'HWY'
COMBINED = 'COMBINED'

# FUEL TYPES
PETROL = 'PETROL'
DIESEL = 'DIESEL'
ELECTRIC = 'ELECTRIC'
LPG = 'LPG'
CNG = 'CNG'

# DRIVE TYPES
REAR = 'REAR'
FRONT = 'FRONT'
ALL_WHEEL_DRIVE = 'AWD'
FOUR_BY_FOUR = '4X4'

TIMESTAMP_FORMAT = '%Y-%m-%d %H:%M:%S'
